#ifndef AXI_COPROCESSOR_INTERFACE_H
#define AXI_COPROCESSOR_INTERFACE_H

struct interface_ioctl_data{
	unsigned int register_offset;
	unsigned int register_value;
};

/* registers */
#define INTERFACE_MINIMAL_REGISTER_SPACE	0x2FFF
#define INTERFACE_CONTROL_REG			0x00
#define INTERFACE_STATUS_REG	 		0x04 
#define INTERFACE_FIFO_IN_DATA_AMOUNT_REG	0x08
#define INTERFACE_FIFO_TRANSFER_STATUS_REG	0x0C
#define INTERFACE_USER_REG_0			0x10
#define INTERFACE_USER_REG_1                    0x14
#define INTERFACE_USER_REG_2                    0x18
#define INTERFACE_USER_REG_3                    0x1C
#define INTERFACE_USER_REG_4                    0x20
#define INTERFACE_USER_REG_5                    0x24

//control
#define INTERFACE_COPY_DATA_TO_FIFO		0x01
#define INTERFACE_COPY_DATA_FROM_FIFO		0x02

//status
#define INTERFACE_FIFO_IN_EMPTY_MASK		1 << 0
#define INTERFACE_FIFO_IN_EMPTY_SHIFT		0
#define INTERFACE_FIFO_IN_FULL_MASK		1 << 1
#define INTERFACE_FIFO_IN_FULL_SHIFT    	1
#define INTERFACE_FIFO_IN_COPYING_MASK		1 << 2
#define INTERFACE_FIFO_IN_COPYING_SHIFT         2
#define INTERFACE_FIFO_OUT_EMPTY_MASK		1 << 3
#define INTERFACE_FIFO_OUT_EMPTY_SHIFT          3
#define INTERFACE_FIFO_OUT_FULL_MASK		1 << 4
#define INTERFACE_FIFO_OUT_FULL_SHIFT           4
#define INTERFACE_FIFO_OUT_COPYING_MASK		1 << 5
#define INTERFACE_FIFO_OUT_COPYING_SHIFT        5

//in fifo data
#define INTERFACE_IN_DATA_AMOUNT_MASK		0x1FF

//fifo transfer status
#define INTERFACE_INPUT_DATA_COPIED_SHIFT	0
#define INTERFACE_INPUT_DATA_COPIED_MASK	0x1FF
#define INTERFACE_OUTPUT_DATA_COPIED_SHIFT	9
#define INTERFACE_OUTPUT_DATA_COPIED_MASK	0x3FE00

/* ioctls */
#define INTERFACE_IOCTL_MAGIC				'I'

#define INTERFACE_SET_USER_REGISTER  			_IOW(INTERFACE_IOCTL_MAGIC, 1, struct interface_ioctl_data *)
#define INTERFACE_GET_USER_REGISTER 			_IOR(INTERFACE_IOCTL_MAGIC, 2, struct interface_ioctl_data *)

#define INTERFACE_GET_FIFO_IN_EMPTY			_IOR(INTERFACE_IOCTL_MAGIC, 3, unsigned char *)
#define INTERFACE_GET_FIFO_IN_FULL			_IOR(INTERFACE_IOCTL_MAGIC, 4, unsigned char *)
#define INTERFACE_GET_FIFO_IN_COPY_STATUS		_IOR(INTERFACE_IOCTL_MAGIC, 5, unsigned char *)
#define INTERFACE_GET_FIFO_IN_COPIED_DATA_AMOUNT	_IOR(INTERFACE_IOCTL_MAGIC, 6, unsigned char *)

#define INTERFACE_GET_FIFO_OUT_EMPTY			_IOR(INTERFACE_IOCTL_MAGIC, 7, unsigned char *)
#define INTERFACE_GET_FIFO_OUT_FULL			_IOR(INTERFACE_IOCTL_MAGIC, 8, unsigned char *)
#define INTERFACE_GET_FIFO_OUT_COPY_STATUS		_IOR(INTERFACE_IOCTL_MAGIC, 9, unsigned char *)
#define INTERFACE_GET_FIFO_OUT_COPIED_DATA_AMOUNT	_IOR(INTERFACE_IOCTL_MAGIC, 10, unsigned char *)

/* misc */
#define INTERFACE_MAJOR_NUMBER			95
#define INTERFACE_FILE_OPENED			1
#define INTERFACE_FILE_CLOSED			0

#endif 
